version: 0.2

phases:
  pre_build:
    commands:
      - echo install
      - npm install 
  build:
    commands:
      - echo install
      - npm run build
artifacts:
  files:
    - build/**/*
    - Scripts/**/*
    - appspec.yml
